### ISSUE TITLE
When a user is removed from the user table, it should also be removed from all the other tables its associated with

### ISSUE THREAD

**Issue by MiloIssueTracker** [RubenJ01/MiloBot#20]
## Steps to Reproduce
By deleting a user from the database
## Severity
3
## Additional Information
This can probably fixed by adding some keys
## Author
`RubenJ01`: 391583287652515841

**Comment by gaborszita** [comment]
This should be solved in the database refactor by adding ON DELETE CASCADE to every foreign key reference.

When adding a foreign key use this syntax:
```
[CONSTRAINT [symbol]] FOREIGN KEY
    [index_name] (index_col_name, ...)
    REFERENCES tbl_name (index_col_name,...)
    [ON DELETE reference_option]
    [ON UPDATE reference_option]
```

Index name can be omitted, and should be, because I tried specifying it when also specifying a constraint symbol and doesn't seem to have any effect on the index name. A constraint symbol, however, should be specified. This is because when dropping a table that has a foreign key constraint, we need to first delete the constraint.

Here's an example:
```
CREATE TABLE author (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE book (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  author_id SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT `fk_book_author`
    FOREIGN KEY (author_id) REFERENCES author (id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;
```

Source: [https://mariadb.com/kb/en/foreign-keys/](https://mariadb.com/kb/en/foreign-keys/)

@RubenJ01

**Comment by RubenJ01** [comment]
This has been resolved with the recent database rework
